default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "1.7.0"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        exclude_types: [html]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        args: ["--no-site-packages"]
  - repo: https://github.com/pycqa/bandit
    rev: "1.7.7"
    hooks:
      - id: bandit
        args: ["--exclude", ".venv,tests"]
  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.7.0
    hooks:
      - id: pip-audit
        args: ["--requirement", "requirements.txt"]
